image:
  file: Dockerfile
checkoutLocation: chromium/src/
ports:
- port: 6080
tasks:
- init: >
    cd /workspace/chromium &&
    pyenv install 3.9.7 &&
    pyenv global 3.9.7 &&
    repo init -u https://chromium.googlesource.com/chromiumos/manifest.git --submodules --depth=1 -b stable -g minilayout && 
    repo sync -j$(nproc) &&
    cros_sdk
